# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_title', models.CharField(max_length=255)),
                ('mov_img', models.CharField(max_length=255)),
                ('mov_release', models.DateField()),
                ('mov_director', models.CharField(max_length=255)),
                ('mov_descript', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watchlist', models.ManyToManyField(related_name='watchlist', to='login.Users')),
            ],
        ),
    ]
