# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.IntegerField(),
        ),
    ]
